name: furniture_inventory
description: "A new Flutter project."
publish_to: "none"

version: 1.0.3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  flutter_native_splash: ^2.4.0
  image_picker: ^1.1.2
  open_filex: ^4.7.0
  package_info_plus: 8.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_launcher_icons: ^0.13.1 # For setting the app icon

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# Configuration for the App Icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/image.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
# أضف هذا القسم الجديد في نهاية الملف
flutter_native_splash:
  # لون الخلفية الذي سيظهر خلف الصورة
  color: "#FFFFFF" # يمكنك استخدام أي لون تريده

  # مسار الصورة التي تريدها أن تظهر في شاشة البداية
  image: assets/images/image.png

  # هذا هو الخيار الأهم لتكبير الصورة لتملأ الشاشة
  android_gravity: fill
  ios_content_mode: scaleAspectFill
